title: Dario Fumarola
logo: /assets/img/logo.png
description: The true mystery of the world is the visible, not the invisible. - Oscar Wilde
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
